### PR TITLE
merge request of the scalable command center and its complying services

### PR DESCRIPTION
**Pull request by Thomas-Yang**
merge pull request for #15.

### CODE REVIEW

**Comment by jhauswald** [comment]
I'm a little concerned about the state of this PR:
- it has 23 commits (I think there was an issue rebasing)
- 1000+ files changed

Even if as described it adds the complying services, why are there so many differences? Are these your java versions replacing the current ones in the repo?
I thought this was just the glue command center and the services were being updated accordingly around it? Let's discuss through this

**Comment by Thomas-Yang** [comment]
I think I was successfully rebased. I can double check whether it is the case. Except the IM service which I have cleaned up to some extent and the Sirius service which serves as a demo to design a workflow interacting with the new command center, other services are just thrift interface changes and glue codes. Let me know the best way you think to get it merged.

Best

Hailong

**Comment by jhauswald** [comment]
I'm trying to get [service_project](https://github.com/Thomas-Yang/service_project) running to test the other services. Im working off your repo since this PR still needs to get cleaned up. I'm having trouble: 

Seems it built fine:
```
Buildfile: /home/jahausw/projects/clarityinc/service_project/commandcenter/build.xml

clean:
   [delete] Deleting directory /home/jahausw/projects/clarityinc/service_project/commandcenter/bin

init:
    [mkdir] Created dir: /home/jahausw/projects/clarityinc/service_project/commandcenter/bin

build:
     [echo] CommandCenter: /home/jahausw/projects/clarityinc/service_project/commandcenter/build.xml
    [javac] Compiling 12 source files to /home/jahausw/projects/clarityinc/service_project/commandcenter/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] 1 warning

jar-cc:
      [jar] Building jar: /home/jahausw/projects/clarityinc/service_project/commandcenter/commandcenter.jar

BUILD SUCCESSFUL
Total time: 1 second
```

But when I use `./start-cc-service.sh`:
```
Exception in thread "main" java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at edu.umich.clarity.service.scheduler.CommandCenter.main(CommandCenter.java:102)
```

My conf has `localhost:8000` set. I'm sure its simple. in the meantime I'll read/compile the other services

**Comment by Thomas-Yang** [comment]
Is your configuration file looks like the one as the example?

https://github.com/Thomas-Yang/service_project/blob/master/commandcenter/conf/conf.properties <https://github.com/Thomas-Yang/service_project/blob/master/commandcenter/conf/conf.properties>

**Comment by Thomas-Yang** [comment]
@jhauswald could you check out the new branch(js-compatible) under the service-project? It should be working fine with the configuration file. I also update the query data structure to be compatible with JS as @twurman mentioned complex data structure is not supported inside map. This affects the other services a little bit since they need to change the manipulation of query data.

**Comment by jhauswald** [comment]
Yes the new branch works! I'll test all the services with it later. Is that the cc that will get merged in then?

**Comment by Thomas-Yang** [comment]
Yes. I am still updating the query data parsing in all the services. Right now you can test ARS and its own client under test-clients. Then I think @Lilisys could help me to update the command line argument parser of all the services before they get merged.

**Comment by Lilisys** [comment]
@Thomas-Yang [here](https://github.com/clarityinc/clarityeco/wiki/ClarityEco-Standard-Command-Line-Arguments) is the basic info for the command line arguments. I'm not sure what parser you'll use if there are non c++ or python services though.

**Comment by jhauswald** [comment]
Hey this Thomas-Yang/service_project@51dff91 seems to be working well with the services, is that what we are eventually going to be merging in?

**Comment by Thomas-Yang** [comment]
@jhauswald It is already compatible with JS and gets rid of the complex data structure inside map.

**Comment by jhauswald** [comment]
Yea I figured -- ok cool good to know it's somewhere :+1:

**Pull request closed without merging**
